BOOL(*wglChoosePixelFormatARB)(HDC hdc,const int *piAttribIList,const FLOAT *pfAttribFList,UINT nMaxFormats,int *piFormats,UINT *nNumFormats);
HGLRC(*wglCreateContextAttribsARB)(HDC hDC,HGLRC hShareContext,const int *attribList);
BOOL(*wglSwapIntervalEXT)(int interval);
void glCullFace(GLenum mode);
void glFrontFace(GLenum mode);
void glHint(GLenum target,GLenum mode);
void glLineWidth(GLfloat width);
void glPointSize(GLfloat size);
void glPolygonMode(GLenum face,GLenum mode);
void glScissor(GLint x,GLint y,GLsizei width,GLsizei height);
void glTexParameterf(GLenum target,GLenum pname,GLfloat param);
void glTexParameterfv(GLenum target,GLenum pname,const GLfloat *params);
void glTexParameteri(GLenum target,GLenum pname,GLint param);
void glTexParameteriv(GLenum target,GLenum pname,const GLint *params);
void glTexImage1D(GLenum target,GLint level,GLint internalformat,GLsizei width,GLint border,GLenum format,GLenum type,const GLvoid *pixels);
void glTexImage2D(GLenum target,GLint level,GLint internalformat,GLsizei width,GLsizei height,GLint border,GLenum format,GLenum type,const GLvoid *pixels);
void glDrawBuffer(GLenum mode);
void glClear(GLbitfield mask);
void glClearColor(GLclampf red,GLclampf green,GLclampf blue,GLclampf alpha);
void glClearStencil(GLint s);
void glClearDepth(GLclampd depth);
void glStencilMask(GLuint mask);
void glColorMask(GLboolean red,GLboolean green,GLboolean blue,GLboolean alpha);
void glDepthMask(GLboolean flag);
void glDisable(GLenum cap);
void glEnable(GLenum cap);
void glFinish(void);
void glFlush(void);
void glBlendFunc(GLenum sfactor,GLenum dfactor);
void glLogicOp(GLenum opcode);
void glStencilFunc(GLenum func,GLint ref,GLuint mask);
void glStencilOp(GLenum fail,GLenum zfail,GLenum zpass);
void glDepthFunc(GLenum func);
void glPixelStoref(GLenum pname,GLfloat param);
void glPixelStorei(GLenum pname,GLint param);
void glReadBuffer(GLenum mode);
void glReadPixels(GLint x,GLint y,GLsizei width,GLsizei height,GLenum format,GLenum type,GLvoid *pixels);
void glGetBooleanv(GLenum pname,GLboolean *params);
void glGetDoublev(GLenum pname,GLdouble *params);
GLenum glGetError(void);
void glGetFloatv(GLenum pname,GLfloat *params);
void glGetIntegerv(GLenum pname,GLint *params);
const GLubyte * glGetString(GLenum name);
void glGetTexImage(GLenum target,GLint level,GLenum format,GLenum type,GLvoid *pixels);
void glGetTexParameterfv(GLenum target,GLenum pname,GLfloat *params);
void glGetTexParameteriv(GLenum target,GLenum pname,GLint *params);
void glGetTexLevelParameterfv(GLenum target,GLint level,GLenum pname,GLfloat *params);
void glGetTexLevelParameteriv(GLenum target,GLint level,GLenum pname,GLint *params);
GLboolean glIsEnabled(GLenum cap);
void glDepthRange(GLclampd zNear,GLclampd zFar);
void glViewport(GLint x,GLint y,GLsizei width,GLsizei height);
void glDrawArrays(GLenum mode,GLint first,GLsizei count);
void glDrawElements(GLenum mode,GLsizei count,GLenum type,const GLvoid *indices);
void glPolygonOffset(GLfloat factor,GLfloat units);
void glCopyTexImage1D(GLenum target,GLint level,GLenum internalFormat,GLint x,GLint y,GLsizei width,GLint border);
void glCopyTexImage2D(GLenum target,GLint level,GLenum internalFormat,GLint x,GLint y,GLsizei width,GLsizei height,GLint border);
void glCopyTexSubImage1D(GLenum target,GLint level,GLint xoffset,GLint x,GLint y,GLsizei width);
void glCopyTexSubImage2D(GLenum target,GLint level,GLint xoffset,GLint yoffset,GLint x,GLint y,GLsizei width,GLsizei height);
void glTexSubImage1D(GLenum target,GLint level,GLint xoffset,GLsizei width,GLenum format,GLenum type,const GLvoid *pixels);
void glTexSubImage2D(GLenum target,GLint level,GLint xoffset,GLint yoffset,GLsizei width,GLsizei height,GLenum format,GLenum type,const GLvoid *pixels);
void glBindTexture(GLenum target,GLuint texture);
void glDeleteTextures(GLsizei n,const GLuint *textures);
void glGenTextures(GLsizei n,GLuint *textures);
GLboolean glIsTexture(GLuint texture);
void(*glDrawRangeElements)(GLenum mode,GLuint start,GLuint end,GLsizei count,GLenum type,const void *indices);
void(*glTexImage3D)(GLenum target,GLint level,GLint internalformat,GLsizei width,GLsizei height,GLsizei depth,GLint border,GLenum format,GLenum type,const void *pixels);
void(*glTexSubImage3D)(GLenum target,GLint level,GLint xoffset,GLint yoffset,GLint zoffset,GLsizei width,GLsizei height,GLsizei depth,GLenum format,GLenum type,const void *pixels);
void(*glCopyTexSubImage3D)(GLenum target,GLint level,GLint xoffset,GLint yoffset,GLint zoffset,GLint x,GLint y,GLsizei width,GLsizei height);
void(*glActiveTexture)(GLenum texture);
void(*glSampleCoverage)(GLfloat value,GLboolean invert);
void(*glCompressedTexImage3D)(GLenum target,GLint level,GLenum internalformat,GLsizei width,GLsizei height,GLsizei depth,GLint border,GLsizei imageSize,const void *data);
void(*glCompressedTexImage2D)(GLenum target,GLint level,GLenum internalformat,GLsizei width,GLsizei height,GLint border,GLsizei imageSize,const void *data);
void(*glCompressedTexImage1D)(GLenum target,GLint level,GLenum internalformat,GLsizei width,GLint border,GLsizei imageSize,const void *data);
void(*glCompressedTexSubImage3D)(GLenum target,GLint level,GLint xoffset,GLint yoffset,GLint zoffset,GLsizei width,GLsizei height,GLsizei depth,GLenum format,GLsizei imageSize,const void *data);
void(*glCompressedTexSubImage2D)(GLenum target,GLint level,GLint xoffset,GLint yoffset,GLsizei width,GLsizei height,GLenum format,GLsizei imageSize,const void *data);
void(*glCompressedTexSubImage1D)(GLenum target,GLint level,GLint xoffset,GLsizei width,GLenum format,GLsizei imageSize,const void *data);
void(*glGetCompressedTexImage)(GLenum target,GLint level,void *img);
void(*glBlendFuncSeparate)(GLenum sfactorRGB,GLenum dfactorRGB,GLenum sfactorAlpha,GLenum dfactorAlpha);
void(*glMultiDrawArrays)(GLenum mode,const GLint *first,const GLsizei *count,GLsizei drawcount);
void(*glMultiDrawElements)(GLenum mode,const GLsizei *count,GLenum type,const void *const*indices,GLsizei drawcount);
void(*glPointParameterf)(GLenum pname,GLfloat param);
void(*glPointParameterfv)(GLenum pname,const GLfloat *params);
void(*glPointParameteri)(GLenum pname,GLint param);
void(*glPointParameteriv)(GLenum pname,const GLint *params);
void(*glBlendColor)(GLfloat red,GLfloat green,GLfloat blue,GLfloat alpha);
void(*glBlendEquation)(GLenum mode);
void(*glGenQueries)(GLsizei n,GLuint *ids);
void(*glDeleteQueries)(GLsizei n,const GLuint *ids);
GLboolean(*glIsQuery)(GLuint id);
void(*glBeginQuery)(GLenum target,GLuint id);
void(*glEndQuery)(GLenum target);
void(*glGetQueryiv)(GLenum target,GLenum pname,GLint *params);
void(*glGetQueryObjectiv)(GLuint id,GLenum pname,GLint *params);
void(*glGetQueryObjectuiv)(GLuint id,GLenum pname,GLuint *params);
void(*glBindBuffer)(GLenum target,GLuint buffer);
void(*glDeleteBuffers)(GLsizei n,const GLuint *buffers);
void(*glGenBuffers)(GLsizei n,GLuint *buffers);
GLboolean(*glIsBuffer)(GLuint buffer);
void(*glBufferData)(GLenum target,GLsizeiptr size,const void *data,GLenum usage);
void(*glBufferSubData)(GLenum target,GLintptr offset,GLsizeiptr size,const void *data);
void(*glGetBufferSubData)(GLenum target,GLintptr offset,GLsizeiptr size,void *data);
void(*glMapBuffer)(GLenum target,GLenum access);
GLboolean(*glUnmapBuffer)(GLenum target);
void(*glGetBufferParameteriv)(GLenum target,GLenum pname,GLint *params);
void(*glGetBufferPointerv)(GLenum target,GLenum pname,void **params);
void(*glBlendEquationSeparate)(GLenum modeRGB,GLenum modeAlpha);
void(*glDrawBuffers)(GLsizei n,const GLenum *bufs);
void(*glStencilOpSeparate)(GLenum face,GLenum sfail,GLenum dpfail,GLenum dppass);
void(*glStencilFuncSeparate)(GLenum face,GLenum func,GLint ref,GLuint mask);
void(*glStencilMaskSeparate)(GLenum face,GLuint mask);
void(*glAttachShader)(GLuint program,GLuint shader);
void(*glBindAttribLocation)(GLuint program,GLuint index,const GLchar *name);
void(*glCompileShader)(GLuint shader);
GLuint(*glCreateProgram)(void);
GLuint(*glCreateShader)(GLenum type);
void(*glDeleteProgram)(GLuint program);
void(*glDeleteShader)(GLuint shader);
void(*glDetachShader)(GLuint program,GLuint shader);
void(*glDisableVertexAttribArray)(GLuint index);
void(*glEnableVertexAttribArray)(GLuint index);
void(*glGetActiveAttrib)(GLuint program,GLuint index,GLsizei bufSize,GLsizei *length,GLint *size,GLenum *type,GLchar *name);
void(*glGetActiveUniform)(GLuint program,GLuint index,GLsizei bufSize,GLsizei *length,GLint *size,GLenum *type,GLchar *name);
void(*glGetAttachedShaders)(GLuint program,GLsizei maxCount,GLsizei *count,GLuint *shaders);
GLint(*glGetAttribLocation)(GLuint program,const GLchar *name);
void(*glGetProgramiv)(GLuint program,GLenum pname,GLint *params);
void(*glGetProgramInfoLog)(GLuint program,GLsizei bufSize,GLsizei *length,GLchar *infoLog);
void(*glGetShaderiv)(GLuint shader,GLenum pname,GLint *params);
void(*glGetShaderInfoLog)(GLuint shader,GLsizei bufSize,GLsizei *length,GLchar *infoLog);
void(*glGetShaderSource)(GLuint shader,GLsizei bufSize,GLsizei *length,GLchar *source);
GLint(*glGetUniformLocation)(GLuint program,const GLchar *name);
void(*glGetUniformfv)(GLuint program,GLint location,GLfloat *params);
void(*glGetUniformiv)(GLuint program,GLint location,GLint *params);
void(*glGetVertexAttribdv)(GLuint index,GLenum pname,GLdouble *params);
void(*glGetVertexAttribfv)(GLuint index,GLenum pname,GLfloat *params);
void(*glGetVertexAttribiv)(GLuint index,GLenum pname,GLint *params);
void(*glGetVertexAttribPointerv)(GLuint index,GLenum pname,void **pointer);
GLboolean(*glIsProgram)(GLuint program);
GLboolean(*glIsShader)(GLuint shader);
void(*glLinkProgram)(GLuint program);
void(*glShaderSource)(GLuint shader,GLsizei count,const GLchar *const*string,const GLint *length);
void(*glUseProgram)(GLuint program);
void(*glUniform1f)(GLint location,GLfloat v0);
void(*glUniform2f)(GLint location,GLfloat v0,GLfloat v1);
void(*glUniform3f)(GLint location,GLfloat v0,GLfloat v1,GLfloat v2);
void(*glUniform4f)(GLint location,GLfloat v0,GLfloat v1,GLfloat v2,GLfloat v3);
void(*glUniform1i)(GLint location,GLint v0);
void(*glUniform2i)(GLint location,GLint v0,GLint v1);
void(*glUniform3i)(GLint location,GLint v0,GLint v1,GLint v2);
void(*glUniform4i)(GLint location,GLint v0,GLint v1,GLint v2,GLint v3);
void(*glUniform1fv)(GLint location,GLsizei count,const GLfloat *value);
void(*glUniform2fv)(GLint location,GLsizei count,const GLfloat *value);
void(*glUniform3fv)(GLint location,GLsizei count,const GLfloat *value);
void(*glUniform4fv)(GLint location,GLsizei count,const GLfloat *value);
void(*glUniform1iv)(GLint location,GLsizei count,const GLint *value);
void(*glUniform2iv)(GLint location,GLsizei count,const GLint *value);
void(*glUniform3iv)(GLint location,GLsizei count,const GLint *value);
void(*glUniform4iv)(GLint location,GLsizei count,const GLint *value);
void(*glUniformMatrix2fv)(GLint location,GLsizei count,GLboolean transpose,const GLfloat *value);
void(*glUniformMatrix3fv)(GLint location,GLsizei count,GLboolean transpose,const GLfloat *value);
void(*glUniformMatrix4fv)(GLint location,GLsizei count,GLboolean transpose,const GLfloat *value);
void(*glValidateProgram)(GLuint program);
void(*glVertexAttrib1d)(GLuint index,GLdouble x);
void(*glVertexAttrib1dv)(GLuint index,const GLdouble *v);
void(*glVertexAttrib1f)(GLuint index,GLfloat x);
void(*glVertexAttrib1fv)(GLuint index,const GLfloat *v);
void(*glVertexAttrib1s)(GLuint index,GLshort x);
void(*glVertexAttrib1sv)(GLuint index,const GLshort *v);
void(*glVertexAttrib2d)(GLuint index,GLdouble x,GLdouble y);
void(*glVertexAttrib2dv)(GLuint index,const GLdouble *v);
void(*glVertexAttrib2f)(GLuint index,GLfloat x,GLfloat y);
void(*glVertexAttrib2fv)(GLuint index,const GLfloat *v);
void(*glVertexAttrib2s)(GLuint index,GLshort x,GLshort y);
void(*glVertexAttrib2sv)(GLuint index,const GLshort *v);
void(*glVertexAttrib3d)(GLuint index,GLdouble x,GLdouble y,GLdouble z);
void(*glVertexAttrib3dv)(GLuint index,const GLdouble *v);
void(*glVertexAttrib3f)(GLuint index,GLfloat x,GLfloat y,GLfloat z);
void(*glVertexAttrib3fv)(GLuint index,const GLfloat *v);
void(*glVertexAttrib3s)(GLuint index,GLshort x,GLshort y,GLshort z);
void(*glVertexAttrib3sv)(GLuint index,const GLshort *v);
void(*glVertexAttrib4Nbv)(GLuint index,const GLbyte *v);
void(*glVertexAttrib4Niv)(GLuint index,const GLint *v);
void(*glVertexAttrib4Nsv)(GLuint index,const GLshort *v);
void(*glVertexAttrib4Nub)(GLuint index,GLubyte x,GLubyte y,GLubyte z,GLubyte w);
void(*glVertexAttrib4Nubv)(GLuint index,const GLubyte *v);
void(*glVertexAttrib4Nuiv)(GLuint index,const GLuint *v);
void(*glVertexAttrib4Nusv)(GLuint index,const GLushort *v);
void(*glVertexAttrib4bv)(GLuint index,const GLbyte *v);
void(*glVertexAttrib4d)(GLuint index,GLdouble x,GLdouble y,GLdouble z,GLdouble w);
void(*glVertexAttrib4dv)(GLuint index,const GLdouble *v);
void(*glVertexAttrib4f)(GLuint index,GLfloat x,GLfloat y,GLfloat z,GLfloat w);
void(*glVertexAttrib4fv)(GLuint index,const GLfloat *v);
void(*glVertexAttrib4iv)(GLuint index,const GLint *v);
void(*glVertexAttrib4s)(GLuint index,GLshort x,GLshort y,GLshort z,GLshort w);
void(*glVertexAttrib4sv)(GLuint index,const GLshort *v);
void(*glVertexAttrib4ubv)(GLuint index,const GLubyte *v);
void(*glVertexAttrib4uiv)(GLuint index,const GLuint *v);
void(*glVertexAttrib4usv)(GLuint index,const GLushort *v);
void(*glVertexAttribPointer)(GLuint index,GLint size,GLenum type,GLboolean normalized,GLsizei stride,const void *pointer);